### PR TITLE
Fix multiple event calls when removing/re-adding same record key

### LINKED ISSUE #36: on('child_changed',...) is being called many times when remove/re-add a record key
`on('child_changed',...)` is being called many times when it probably shouldn't.

I'm opening four different issues because I'm not sure if they are related and, if they are not, they can be fixed separately. However, I used the same Plunker to simulate all of them, so it is a little bigger than usual. I tried to explain everything in the comments, but if something is not clear enough, just let me know.

http://plnkr.co/edit/Y0mp2XDtSQ0Pz9ClXctZ

### PR DESCRIPTION
**Pull request by katowulf**
This mostly fixes #36 so that `child_changed` and `value` events are not called redundantly. The core problem was that [the old unwatch() call did not reference the correctly bound function ref](https://github.com/firebase/firebase-util/compare/kato-child_changed?expand=1#diff-9a6aea2f62f66b0d43625eec94fdb0e8L217). 

A secondary, more subtle, issue was that changes to the records may trigger value events, although the data being displayed to the client (which is determined by the `select()` clause) may not actually changed. I added a check into the AbstractRecord's `_trigger()` event to ensure value events are only triggered at appropriate times.

There are still a couple of edge cases where child_changed events can be triggered multiple times, such as when I manually delete the merged paths one-by-one, and do not start with the master record (this will result in a child_changed event for each secondary path, followed by a final one with `null` when the master is removed. These are appropriate and we don't have a way to distinguish these from normal changes to the data (i.e. we can't tell the users' intent and we can't wait indefinitely to see if they other paths are deleted because this mucks with the timing of events and ordering).

### CODE REVIEW

**Comment by katowulf** [comment]
@jwngr if you have time, please give this a brief review.

File: src/NormalizedCollection/libs/RecordSetEventManager.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ RecordList.prototype = {
     util.log.debug('RecordList.add: key=%s, prevChild=%s', key, prevChild);
     var rec = this.obs.child(key);
     var fn = util.bind(this._valueUpdated, this, key);
-    this.loading[key] = {rec: rec, prev: prevChild, fn: fn};
+    this.loading[key] = {rec: rec, prev: prevChild, fn: fn, unwatch: function() { rec.unwatch('value', fn); }};
```
Comment (katowulf) [inline src/NormalizedCollection/libs/RecordSetEventManager.js]: Added an unwatch() function directly to the data we store to avoid complications with unwatching later.

The process looks like so:
  - store the rec/prevChild/and callback function in `this.loading` until the record is merged and returned
  - once it is returned, move the ref from `this.loading` into `this.recs` for monitoring
  - trigger a `child_added` event
  - trigger a `value` event

We also store and synchronize an ordered list of keys in `this.keys`. We use this to calculate the previous child key, since our `prevChild` from the Firebase event may not exist locally after we apply filtering.

File: src/NormalizedCollection/libs/RecordSet.js [hunk 2]
```diff
@@ -74,13 +74,16 @@ util.inherits(RecordSet, AbstractRecord, {
...
    */
   mergeData: function(snaps, isExport) {
-    var self = this;
-    var out = {};
-    util.each(snaps, function(snap) {
-      if( snap.val() !== null && self.filters.test(snap.val(), snap.key(), snap.getPriority()) ) {
-        out[snap.key()] = isExport? snap.exportVal() : snap.val();
-      }
-    });
+    var self = this, out = null;
```
Comment (katowulf) [inline src/NormalizedCollection/libs/RecordSet.js]: This fixes an inconsistency with the Firebase SDK. When the value is `null` firebase-util was incorrectly returning an object with `{.value, .priority}` but Firebase only returns null (there is no priority for a null value).

File: src/NormalizedCollection/libs/AbstractRecord.js [hunk 3]
```diff
@@ -231,6 +232,12 @@ AbstractRecord.prototype = {
       id = null;
       ref = this.getRef();
       prev = null;
```
Comment (katowulf) [inline src/NormalizedCollection/libs/AbstractRecord.js]: This is the check to ensure that we don't send redundant `value` events.

File: src/NormalizedCollection/libs/Record.js [hunk 4]
```diff
@@ -94,16 +94,23 @@ util.inherits(Record, AbstractRecord, {
...
   mergeData: function(snaps, isExport) {
-    var map = this.getFieldMap();
-    var data = util.extend.apply(null, util.map(snaps, function(ss) {
-      return map.extractData(ss, isExport);
-    }));
-    if( isExport && snaps.length > 0 && snaps[0].getPriority() !== null ) {
-      if( !util.isObject(data) ) {
-        data = {'.value': data};
+    var data = null, map = this.getFieldMap();
+
```
Comment (katowulf) [inline src/NormalizedCollection/libs/Record.js]: This fixes an error where we incorrectly returned an object with `{.value, .priority}` if the final value was null and `exportVal()` was called. That doesn't match the Firebase SDK (null values have no priority) and Firebase just returns `null`.

**Comment by jwngr** [comment]
Gave this a cursory look and it looks good. I don't fully understand everything that's going on in this code, but you told me not to try to figure it all out. But things in general look good.
